export default wordList = [
  { word: "HTML", hint: "Markup language for web pages" },
  { word: "CSS", hint: "Stylesheets for web design" },
  { word: "JavaScript", hint: "Popular web scripting language" },
  { word: "React", hint: "JavaScript library for UI" },
  { word: "Bootstrap", hint: "CSS framework for responsive design" },
  { word: "Angular", hint: "JavaScript framework by Google" },
  { word: "Vue", hint: "Progressive JavaScript framework" },
  { word: "jQuery", hint: "JavaScript library for easier DOM manipulation" },
  { word: "AJAX", hint: "Technique for asynchronous web requests" },
  { word: "JSON", hint: "Data format for web APIs" },
  { word: "API", hint: "Interface for web services" },
  { word: "PHP", hint: "Server-side scripting language" },
  { word: "MySQL", hint: "Popular relational database" },
  { word: "MongoDB", hint: "NoSQL database" },
  { word: "GraphQL", hint: "Query language for APIs" },
  { word: "NPM", hint: "Package manager for Node.js" },
  { word: "TypeScript", hint: "Superset of JavaScript" },
  { word: "Express", hint: "Web framework for Node.js" },
  { word: "SEO", hint: "Optimizing for search engines" },
  { word: "REST", hint: "Web service architecture" },
  { word: "HTTPS", hint: "Secure web protocol" },
  { word: "SSL", hint: "Protocol for encrypting web traffic" },
  { word: "CORS", hint: "Cross-Origin Resource Sharing" },
  { word: "Tailwind", hint: "Utility-first CSS framework" },
  { word: "GitHub", hint: "Most popular code hosting platform" },
  { word: "Electron", hint: "Framework for building desktop apps" },
  { word: "UX", hint: "User Experience" },
  { word: "UI", hint: "User Interface" },
  { word: "Python", hint: "Popular high-level programming language" },
  { word: "Ruby", hint: "Dynamic programming language focused on simplicity" },
  { word: "Java", hint: "Widely-used object-oriented programming language" },
  { word: "Swift", hint: "Programming language for iOS and macOS" },
  {
    word: "Kotlin",
    hint: "Modern programming language for Android development",
  },
  { word: "Go", hint: "Statically typed language by Google" },
  { word: "Rust", hint: "System programming language focused on safety" },
  { word: "Perl", hint: "High-level, general-purpose programming language" },
  {
    word: "Scala",
    hint: "Language combining object-oriented and functional programming",
  },
  { word: "Elixir", hint: "Dynamic language for scalable applications" },
  { word: "Lua", hint: "Lightweight scripting language" },
  { word: "MATLAB", hint: "Language for numerical computing" },
  { word: "R", hint: "Language for statistical computing" },
  { word: "SQL", hint: "Language for managing databases" },
  { word: "Bash", hint: "Unix shell and command language" },
  { word: "Shell", hint: "Command language interpreter" },
  { word: "Powershell", hint: "Task automation framework by Microsoft" },
  { word: "Fortran", hint: "Language for numerical and scientific computing" },
  { word: "Assembly", hint: "Low-level programming language" },
  { word: "Scratch", hint: "Visual programming language for beginners" },
  { word: "Dart", hint: "Language optimized for UI" },
];
